receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  logging:
    loglevel: warn
  prometheus:
    endpoint: "0.0.0.0:8889"

processors:
  batch:

extensions:
  health_check:

service:
  telemetry:
    logs:
      level: "warn"
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]